name: Dartle CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: dartle-linux
          - os: macOS-latest
            output-name: dartle-mac
          - os: windows-latest
            output-name: dartle-windows.exe

    steps:
    - uses: DanTup/gh-actions/setup-dart@master
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: dart pub get
    - name: Compile native
      run: mkdir binaries && dart compile exe bin/hello_world.dart -o binaries/${{ matrix.output-name }}
    - uses: actions/upload-artifact@v1
      with:
        name: native-executables
        path: binaries

