name: Dartle CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: hello_world_linux
          - os: macOS-latest
            output-name: hello_world_darwin
          - os: windows-latest
            output-name: hello_world_win.exe

    steps:
    - uses: DanTup/gh-actions/setup-dart@master
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: dart pub get
    - name: Compile native
      run: mkdir binaries && dart compile exe bin/hello_world.dart -o binaries/${{ matrix.output-name }}
    - uses: actions/upload-artifact@v1
      with:
        name: native-executables
        path: binaries

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: binaries/${{ matrix.output-name }}
        asset_name: ${{ matrix.output-name }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"

